name: Build and deploy Python project to Azure Function App - bg-road-fines-checker

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '/home/site/wwwroot'
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Optional: run local tests
      # - name: Install and test locally
      #   run: |
      #     pip install -r requirements.txt
      #     pytest

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_756337FB69474A33BDA0041102696470 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_60421C7909B7431890FD2F637D9B85C7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_06AB82990BD049F4A31900E0398D8606 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'bg-road-fines-checker'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
